name = "template"
description = "for examples"
version = "0.1.0-dev"

authors = ["R Srinivasan"]
maintainers = ["R Srinivasan <rajasrinivasan@hotmail.com>"]
maintainers-logins = ["rajasrinivasan"]
licenses = "MIT"
website = ""
tags = []

executables = ["template"]
