stages:
  - gettools
  - build

variables:
  ADA_PROJECT_PATH: $CI_PROJECT_DIR/adalib
  TOOLS_PATH: $CI_PROJECT_DIR/bin
  EXAMPLES_PATH: $CI_PROJECT_DIR/examples
  ARTIFACTS_PATH: $ADA_PROJECT_PATH/bin
  ALIRE_PATH: $CI_PROJECT_DIR/alire
  GIT_SUBMODULE_STRATEGY: recursive


before_script:
  - apt-get update -qy
  - apt-get install -y gnat
  - apt-get install -y gprbuild
  - apt-get install -y curl
  - git clone --recurse-submodules https://github.com/alire-project/alire.git
  - cd alire
  - dev/build.sh
  - cd ..

build:
  stage: build
  script:
    - cd $ADA_PROJECT_PATH/
    - $ALIRE_PATH/bin/alr -n build
    - export PATH=$PATH:$ALIRE_PATH/bin
    - cd $EXAMPLES_PATH
    - source build.sh
  artifacts:
    paths:
      - $EXAMPLES_PATH/bin/*

getcodemd:
  stage: gettools
  script:
    - >
      curl --header "PRIVATE-TOKEN: $GETARTIFACTS" \
           --location \
           "https://gitlab.com/api/v4/projects/ada23%2Fcodemd/jobs/artifacts/main/download?job=build" \
           --output other.zip
    - unzip other.zip -d $TOOLS_PATH
