stages:
  - build
  - test

variables:
  ADA_PROJECT_PATH: $CI_PROJECT_DIR/adalib
  EXAMPLES_PATH: $CI_PROJECT_DIR/examples
  ARTIFACTS_PATH: $ADA_PROJECT_PATH/bin
  ALIRE_PATH: $CI_PROJECT_DIR/alire
  GIT_SUBMODULE_STRATEGY: recursive


before_script:
  - apt-get update -qy
  - apt-get install -y gnat
  - apt-get install -y gprbuild
  - git clone --recurse-submodules https://github.com/alire-project/alire.git
  - cd alire
  - dev/build.sh
  - cd ..

build:
  stage: build
  script:
    - cd $ADA_PROJECT_PATH/
    - $ALIRE_PATH/bin/alr -n build
    - cd $ADA_PROJECT_PATH

  artifacts:
    paths:
      - $ARTIFACTS_PATH/*

test:
  stage: test
  script:
    - cd $EXAMPLES_PATH/print
    - $ALIRE_PATH/bin/alr -n build
    - cd $EXAMPLES_PATH/print/test
    - source test.sh
    
  dependencies:
    - build

