/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SIMPLE_PB_H_INCLUDED
#define PB_SIMPLE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _msgtime {
    uint32_t seq;
    float now;
} msgtime;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define msgtime_init_default                     {0, 0}
#define msgtime_init_zero                        {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define msgtime_seq_tag                          1
#define msgtime_now_tag                          2

/* Struct field encoding specification for nanopb */
#define msgtime_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   seq,               1) \
X(a, STATIC,   REQUIRED, FLOAT,    now,               2)
#define msgtime_CALLBACK NULL
#define msgtime_DEFAULT NULL

extern const pb_msgdesc_t msgtime_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define msgtime_fields &msgtime_msg

/* Maximum encoded size of messages (where known) */
#define SIMPLE_PB_H_MAX_SIZE                     msgtime_size
#define msgtime_size                             11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
