name = "dglogs"
description = "Log server - datagram logs"
version = "0.1.0-dev"

authors = ["R Srinivasan"]
maintainers = ["R Srinivasan <rajasrinivasan@hotmail.com>"]
maintainers-logins = ["rajasrinivasan"]
licenses = "MIT"
website = ""
tags = []

executables = ["dglogs"]

[build-switches]
"*".style_checks = "No"

