name = "integ"
description = "Data Integrity examples"
version = "0.1.0-dev"

authors = ["R Srinivasan"]
maintainers = ["R Srinivasan <rajasrinivasan@hotmail.com>"]
maintainers-logins = ["rajasrinivasan"]
licenses = "MIT"
website = ""
tags = []

executables = ["integ"]

[build-switches]
"*".style_checks = "No"