name = "gitrev"
description = "Revision Number management for git repositories"
version = "0.1.0-dev"

authors = ["R Srinivasan"]
maintainers = ["R Srinivasan <rajasrinivasan@hotmail.com>"]
maintainers-logins = ["rajasrinivasan"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["gitrev"]
[build-switches]
"*".style_checks = "No"

[[depends-on]]
semantic_versioning = "^2.1.0"
