name = "vrex"
description = "Validate text against regular expressions"
version = "0.1.0-dev"

authors = ["R Srinivasan"]
maintainers = ["R Srinivasan <rajasrinivasan@hotmail.com>"]
maintainers-logins = ["rajasrinivasan"]
licenses = "MIT"
website = ""
tags = []

executables = ["vrex"]

[build-switches]
"*".style_checks = "No"