name: Build with DevOps Container

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/rajasrinivasan/devops:main

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd adalib ; alr --non-interactive build

